#ifndef _STD_MEMCONSTANTS_INCLUDED
#define _STD_MEMCONSTANTS_INCLUDED

#include <std/base/types.h>

#define STD_MEM_BYTE (u64)1
#define STD_MEM_KILOBYTE (u64)(1024 * STD_MEM_BYTE)
#define STD_MEM_MEGABYTE (u64)(1024 * STD_MEM_KILOBYTE)
#define STD_MEM_GIGABYTE (u64)(1024 * STD_MEM_MEGABYTE)
#define STD_MEM_TERABYTE (u64)(1024 * STD_MEM_GIGABYTE)

#define STD_MEM_KILO_BYTE_SI (u64)(1000 * STD_MEM_BYTE)
#define STD_MEM_MEGABYTE_SI (u64)(1000 * STD_MEM_KILOBYTE_SI)
#define STD_MEM_GIGABYTE_SI (u64)(1000 * STD_MEM_MEGABYTE_SI)
#define STD_MEM_TERABYTE_SI (u64)(1000 * STD_MEM_GIGABYTE_SI)

#define STD_MEM_B STD_MEM_BYTE
#define STD_MEM_KB STD_MEM_KILOBYTE
#define STD_MEM_MB STD_MEM_MEGABYTE
#define STD_MEM_GB STD_MEM_GIGABYTE
#define STD_MEM_TB STD_MEM_TERABYTE

#endif

