#ifndef _STD_MEMORYCONSTANTS_INCLUDED
#define _STD_MEMORYCONSTANTS_INCLUDED

#include <std/types.h>

#define STD_MEM_BYTE (u64)1
#define STD_MEM_KILOBYTE (u64)(1024 * STD_MEM_BYTE)
#define STD_MEM_MEGABYTE (u64)(1024 * STD_MEM_KILOBYTE)
#define STD_MEM_GIGABYTE (u64)(1024 * STD_MEM_MEGABYTE)
#define STD_MEM_TERABYTE (u64)(1024 * STD_MEM_GIGABYTE)

#define STD_MEM_KILO_BYTE_SI (u64)(1000 * STD_MEM_BYTE)
#define STD_MEM_MEGABYTE_SI (u64)(1000 * STD_MEM_KILOBYTE_SI)
#define STD_MEM_GIGABYTE_SI (u64)(1000 * STD_MEM_MEGABYTE_SI)
#define STD_MEM_TERABYTE_SI (u64)(1000 * STD_MEM_GIGABYTE_SI)

#define STD_MEM_B STD_MEM_BYTE
#define STD_MEM_KB STD_MEM_KILOBYTE
#define STD_MEM_MB STD_MEM_MEGABYTE
#define STD_MEM_GB STD_MEM_GIGABYTE
#define STD_MEM_TB STD_MEM_TERABYTE

#ifndef STD_DISALLOW_GLOBAL_NAMESPACE
	#define MEM_BYTE STD_MEM_BYTE
	#define MEM_KILOBYTE STD_MEM_KILOBYTE
	#define MEM_MEGABYTE STD_MEM_MEGABYTE
	#define MEM_GIGABYTE STD_MEM_GIGABYTE
	#define MEM_TERABYTE STD_MEM_TERABYTE
	#define MEM_KILO_BYTE_SI STD_MEM_KILO_BYTE_SI
	#define MEM_MEGABYTE_SI STD_MEM_MEGABYTE_SI
	#define MEM_GIGABYTE_SI STD_MEM_GIGABYTE_SI
	#define MEM_TERABYTE_SI STD_MEM_TERABYTE_SI
	#define MEM_B STD_MEM_B
	#define MEM_KB STD_MEM_KB
	#define MEM_MB STD_MEM_MB
	#define MEM_GB STD_MEM_GB
	#define MEM_TB STD_MEM_TB
#endif

#endif

