#ifndef _STD_WINDOWSCONSTANTS_INCLUDED
#define _STD_WINDOWSCONSTANTS_INCLUDED

#include <std/windows/types.h>

#define STD_WINDOWS_PAGE_NOACCESS 0x01
#define STD_WINDOWS_PAGE_READONLY 0x02
#define STD_WINDOWS_PAGE_READWRITE 0x04
#define STD_WINDOWS_PAGE_EXECUTE 0x10
#define STD_WINDOWS_PAGE_EXECUTE_READ 0x20
#define STD_WINDOWS_PAGE_EXECUTE_READWRITE 0x40

#define STD_WINDOWS_MEM_COMMIT 0x00001000

#define STD_WINDOWS_MEM_RELEASE 0x00008000

#define STD_WINDOWS_CP_UTF8 65001

#define STD_WINDOWS_STD_INPUT_HANDLE ((std_DWORD)-10)
#define STD_WINDOWS_STD_OUTPUT_HANDLE ((std_DWORD)-11)
#define STD_WINDOWS_STD_ERROR_HANDLE ((std_DWORD)-12)

#endif


